sudo: required
services:
  - docker

before_install:
  - docker build -t pedrotfs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pedrotfs/react-test npm test -- --coverage

after_success:
  - docker build -t pedrotfs/multi-client ./client
  - docker build -t pedrotfs/multi-server ./server
  - docker build -t pedrotfs/multi-worker ./worker
  - docker build -t pedrotfs/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pedrotfs/multi-client
  - docker push pedrotfs/multi-server
  - docker push pedrotfs/multi-worker
  - docker push pedrotfs/multi-nginx

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-342342342342
#  bucket_path: multi-docker
#  on:
#    branch: master
#  access_key_id:
#    secure: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECURE_KEY